### ISSUE TITLE
mkregs.py

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-lib#591] opened 2023-07-04 23:13 UTC
the instance should connect to top-level ios, not internal wires 

.iob_avalid_i(iob_avalid_i) 

not 

.iob_avalid_i(iob_avalid) 

This is because conversion to the interface types should only occur in the wrappers

**Comment by AndreMerendeira** [comment] 2023-07-07 13:14
This is a duplicate of Issue #577

**Closed** 2023-07-08 01:54 UTC
