### ISSUE TITLE
interfaces  clkrst and  clkrsten should be generated so we can add a prefix

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-lib#590] opened 2023-07-04 23:10 UTC

**Comment by arturum1** [comment] 2023-07-05 19:46
Duplicate of https://github.com/IObundle/iob-lib/issues/552

**Comment by P-Miranda** [comment] 2023-07-14 08:49
Issue addressed in IObundle/iob-lib#604

**Closed** 2023-07-14 09:15 UTC

**Comment by jjts** [comment] 2023-08-06 19:27
Issue not fully addressed. #552 was reopened
